// Node equivalent of tools/stamp_version.py for CI builds (Workers Builds sets WORKERS_CI_COMMIT_SHA).
const fs = require("fs"), path = require("path"), { execSync } = require("child_process");
const root = path.resolve(__dirname, "..");
const version = fs.readFileSync(path.join(root, "VERSION"), "utf8").trim();
let commit = (process.env.WORKERS_CI_COMMIT_SHA || "").slice(0, 7);
if (!commit) { try { commit = execSync("git rev-parse --short HEAD", { cwd: root }).toString().trim(); } catch { commit = "local"; } }
const branch = process.env.WORKERS_CI_BRANCH || "";
const info = { version, build: commit, date: new Date().toISOString().slice(0, 10), engine: "rust-wasm", branch };
const label = `Forever Sims v${version} · build ${commit} · ${info.date}` + (branch && branch !== "main" ? ` · ${branch}` : "");
fs.writeFileSync(path.join(root, "web", "version.js"),
  "// Generated by tools/stamp_version.js\n" +
  `window.FOREVER_SIMS_VERSION = ${JSON.stringify(info)};\n` +
  `document.addEventListener("DOMContentLoaded", () => { const el = document.createElement("div"); el.className = "site-version"; el.title = "Forever Sims build"; el.textContent = ${JSON.stringify(label)}; document.body.append(el); });\n`);
console.log("web/version.js:", info);
