// Node equivalent of tools/stamp_version.py for CI builds (Workers Builds sets WORKERS_CI_COMMIT_SHA).
const fs = require("fs"), path = require("path"), { execSync } = require("child_process");
const root = path.resolve(__dirname, "..");
const version = fs.readFileSync(path.join(root, "VERSION"), "utf8").trim();
let commit = (process.env.WORKERS_CI_COMMIT_SHA || "").slice(0, 7);
if (!commit) { try { commit = execSync("git rev-parse --short HEAD", { cwd: root }).toString().trim(); } catch { commit = "local"; } }
const branch = process.env.WORKERS_CI_BRANCH || "";
const info = { version, build: commit, date: new Date().toISOString().slice(0, 10), engine: "rust-wasm", branch };
const label = `Forever Sims v${version} · build ${commit} · ${info.date}` + (branch && branch !== "main" ? ` · ${branch}` : "");
fs.writeFileSync(path.join(root, "web", "version.js"),
  "// Generated by tools/stamp_version.js\n" +
  `window.FOREVER_SIMS_VERSION = ${JSON.stringify(info)};\n` +
  `document.addEventListener("DOMContentLoaded", () => { const el = document.createElement("div"); el.className = "site-version"; el.title = "Forever Sims build"; el.textContent = ${JSON.stringify(label)}; document.body.append(el); });\n`);
console.log("web/version.js:", info);

// Bump the engine/catalog cache-busting query string so returning visitors' browsers
// (and Cloudflare's edge cache) actually fetch the new wasm/js instead of serving a
// stale cached response forever at an unchanging "?v=1" URL.
const workerPath = path.join(root, "web", "sim-worker.js");
const workerSrc = fs.readFileSync(workerPath, "utf8").replace(/\?v=[^"']+/g, `?v=${commit}`);
fs.writeFileSync(workerPath, workerSrc);
console.log(`web/sim-worker.js: cache-busted to ?v=${commit}`);

// The client and HTML must also change URLs, otherwise a cached client keeps
// requesting an old worker even after the worker's internal URLs are updated.
const clientPath = path.join(root, "web", "sim-client.js");
fs.writeFileSync(clientPath, fs.readFileSync(clientPath, "utf8").replace(/const VERSION = "[^"]+"/, `const VERSION = "${commit}"`));
for (const name of fs.readdirSync(path.join(root, "web")).filter(n => n.endsWith(".html"))) {
  const file = path.join(root, "web", name);
  fs.writeFileSync(file, fs.readFileSync(file, "utf8").replace(/((?:src|href)="\/[^"?]+\.(?:js|css))(?:\?v=[^"]*)?"/g, `$1?v=${commit}"`));
}
for (const name of fs.readdirSync(path.join(root, "web")).filter(n => n.endsWith(".js"))) {
  const file = path.join(root, "web", name);
  fs.writeFileSync(file, fs.readFileSync(file, "utf8").replace(/(["'])(\/data\/[^"'?]+\.json)(?:\?v=[^"']*)?\1/g, (_, quote, url) => `${quote}${url}?v=${commit}${quote}`));
}
