// Generated by tools/stamp_version.js
window.FOREVER_SIMS_VERSION = {"version":"0.21.0","build":"33f8e18","date":"2026-09-22","engine":"rust-wasm","branch":""};
document.addEventListener("DOMContentLoaded", () => { const el = document.createElement("div"); el.className = "site-version"; el.title = "Forever Sims build"; el.textContent = "Forever Sims v0.21.0 · build 33f8e18 · 2026-09-22"; document.body.append(el); });
