// Generated by tools/stamp_version.js
window.FOREVER_SIMS_VERSION = {"version":"0.15.0","build":"96a6c87","date":"2026-09-18","engine":"rust-wasm","branch":""};
document.addEventListener("DOMContentLoaded", () => { const el = document.createElement("div"); el.className = "site-version"; el.title = "Forever Sims build"; el.textContent = "Forever Sims v0.15.0 · build 96a6c87 · 2026-09-18"; document.body.append(el); });
