// Generated by tools/stamp_version.js
window.FOREVER_SIMS_VERSION = {"version":"0.20.0","build":"71017c6","date":"2026-09-22","engine":"rust-wasm","branch":""};
document.addEventListener("DOMContentLoaded", () => { const el = document.createElement("div"); el.className = "site-version"; el.title = "Forever Sims build"; el.textContent = "Forever Sims v0.20.0 · build 71017c6 · 2026-09-22"; document.body.append(el); });
